In [2]:
import numpy as np

x = np.random.rand()
y = np.random.randint(10, 20, [5, 5])

    np.random.randint(   10,    20,   [5, 5]) 👈 size 5x5
                        👆      👆
                        low     high

In [3]:
x, y

(0.5826724426857179,
 array([[15, 19, 16, 12, 17],
        [15, 19, 18, 15, 14],
        [11, 16, 18, 14, 12],
        [13, 11, 12, 19, 14],
        [17, 17, 13, 14, 10]]))

### `numpy.hstack() `

```
Syntax : numpy.hstack(tuple)

Parameters :
tuple : 
        [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the    same shape along all but the second axis.

Return : 
       [stacked ndarray] The stacked array of the input arrays.
```

In [11]:
import numpy as np

first = np.random.randint(low=10, high=20, size=[5, 4])
second = np.random.randint(low=10, high=20, size=[5, 4])


HorizontalStack = np.hstack([first, second])
VerticalStack = np.vstack([first, second])


print(HorizontalStack, f' shape: {HorizontalStack.shape}')
print()
print(VerticalStack, f' shape: {VerticalStack.shape}')



[[19 15 13 15 14 12 10 13]
 [18 11 16 14 15 14 11 11]
 [15 17 18 17 13 12 12 16]
 [11 11 11 12 10 17 14 10]
 [18 12 17 11 15 18 12 15]]  shape: (5, 8)

[[19 15 13 15]
 [18 11 16 14]
 [15 17 18 17]
 [11 11 11 12]
 [18 12 17 11]
 [14 12 10 13]
 [15 14 11 11]
 [13 12 12 16]
 [10 17 14 10]
 [15 18 12 15]]  shape: (10, 4)


### `numpy.concatenate`

In [22]:
import numpy as np

first = np.random.randint(low=10, high=20, size=[5, 4])
second = np.random.randint(low=10, high=20, size=[5, 4])

"""
np.concatenate()
Parameters:

a1, a2, ...: sequence of array like
            he arrays must have the same shape, 
            except in the dimension corresponding to axis (the first, by default).

axis(int):  optional
            The axis along which the arrays will be joined. 
            If axis is None, arrays are flattened before use. Default is 0.
"""

alongCol = np.concatenate([first, second], axis=1)
alongRow = np.concatenate([first, second], axis=0)
"""
axis=1 👈 direction along the column
axis=0 👈 direction along the row
"""

alongRow, alongCol

(array([[13, 17, 19, 11],
        [11, 13, 13, 19],
        [18, 13, 10, 11],
        [11, 19, 12, 19],
        [17, 19, 13, 15],
        [16, 18, 17, 19],
        [14, 18, 18, 19],
        [11, 11, 10, 12],
        [19, 11, 10, 14],
        [17, 19, 18, 13]]),
 array([[13, 17, 19, 11, 16, 18, 17, 19],
        [11, 13, 13, 19, 14, 18, 18, 19],
        [18, 13, 10, 11, 11, 11, 10, 12],
        [11, 19, 12, 19, 19, 11, 10, 14],
        [17, 19, 13, 15, 17, 19, 18, 13]]))

    array([[13, 17, 19, 11],  👈  60
           [11, 13, 13, 19],  👈  56
           [18, 13, 10, 11],  👈  52
           [11, 19, 12, 19],  👈  61
           [17, 19, 13, 15]]) 👈  64


```
>>> np.sum(first, axis=1)
array([60, 56, 52, 61, 64])
```

### `reshape`

In [32]:
Reshaped_Array = first.reshape((2, 10))

first[0, 0] = 1000

Reshaped_Array

array([[1000,   17,   19,   11,   11,   13,   13,   19,   18,   13],
       [  10,   11,   11,   19,   12,   19,   17,   19,   13,   15]])

**Broadcasting Operation**

In [36]:
Copied_Array = Reshaped_Array.copy()

Copied_Array[0] = 1000

Copied_Array

array([[1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
       [  10,   11,   11,   19,   12,   19,   17,   19,   13,   15]])